# Generated by Django 5.1.3 on 2024-11-13 13:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('finished', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('day', models.IntegerField(help_text='Dia 1 de 30 para o desafio de 30 dias.', validators=[django.core.validators.MaxValueValidator(30)])),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='todolist.activity')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
